services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Francoisvaillant\WordpressApiBundle\WordpressApiGetter:
    public: true
    arguments:
      $baseUrl: '%wordpress_api.base_url%'

