services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Francoisvaillant\WordpressApiBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Tests,Kernel.php}'

  Francoisvaillant\WordpressApiBundle\WordpressApiGetter:
    public: true
    arguments:
      $baseUrl: '%wordpress_api.base_url%'

